name: Build on PR

on:
    workflow_dispatch:
    push:
        branches:
            - feature/project-routes
            - feature/ci-cd

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-south-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker image
              run: |
                cd build-server
                echo AWS_REGION=ap-south-1 >> .env
                echo AWS_ACCOUNT_ID=022005599044 >> .env
                echo ECR_REPO_NAME=builder-server >> .env
                npm run login
                npm run build
                npm run tag
                npm run push
               